src/test/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponWalletServiceTest.java
[WOOCOU-37](https://maenguin.atlassian.net/browse/WOOCOU-37)
* CouponWalletService의 allocateCouponToCustomer 메서드 테스트를 추가했습니다.
* allocateCouponToCustomer 메서드는 이미 생성되어 있는 쿠폰들을 고객에게 할당하는 메서드 입니다
테스트 코드 작성하는거 너무 어렵네요 ㅎㅎ..
=> [WOOCOU-37] 🚦 test : 쿠폰 발급 서비스 테스트 코드 추가

src/test/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionServiceTest.java
[WOOCOU-58](https://maenguin.atlassian.net/browse/WOOCOU-58)
테스트 실패하는 부분 방금 발견해서 빠르게 수정했습니다.
- mock 쿠폰의 ExpirationPeriod가 널이어서 났습니다. 다 mock 하려다가 별로인 것 같아서 후다닥 했는데 의견 주세요!
=> [WOOCOU-58] 🚦 test : 쿠폰 리뎀션 서비스 테스트 fail 수정

src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestControllerTest.java, src/test/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionServiceTest.java
[WOOCOU-59](https://maenguin.atlassian.net/browse/WOOCOU-59)
* EntityManager에 접근제한자를 빼먹었는데 마르코님 리뷰를 받고 추가했습니다.
* 이미 등록한 쿠폰코드에 대한 테스트를 추가했습니다. (컨트롤러와 서비스)
=> [WOOCOU-59] 🚦 test : 이미 등록한 쿠폰코드 재등록에 대한 테스트 추가

src/main/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestController.java, src/main/java/com/coumin/woowahancoupons/coupon/controller/CouponRestController.java, src/main/java/com/coumin/woowahancoupons/coupon/dto/CouponCreateRequestDto.java, src/main/java/com/coumin/woowahancoupons/coupon/dto/CouponCreateResponseDto.java, src/main/java/com/coumin/woowahancoupons/coupon/dto/StoreCouponSaveDto.java, src/main/java/com/coumin/woowahancoupons/coupon/service/CouponRedemptionService.java, src/main/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionService.java, src/main/java/com/coumin/woowahancoupons/customer/service/SimpleCustomerService.java, src/main/java/com/coumin/woowahancoupons/domain/BaseEntity.java, src/main/java/com/coumin/woowahancoupons/domain/coupon/Coupon.java, src/main/java/com/coumin/woowahancoupons/domain/coupon/DiscountType.java, src/main/java/com/coumin/woowahancoupons/domain/coupon/IssuerType.java, src/main/java/com/coumin/woowahancoupons/domain/store/Store.java, src/main/java/com/coumin/woowahancoupons/global/ApiResponse.java, src/main/java/com/coumin/woowahancoupons/global/error/GlobalExceptionHandler.java, src/main/java/com/coumin/woowahancoupons/global/exception/CouponRedemptionNotFoundException.java, src/main/java/com/coumin/woowahancoupons/store/service/SimpleStoreService.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestControllerTest.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRestControllerTest.java
[WOOCOU-53](https://maenguin.atlassian.net/browse/WOOCOU-53)
탭 인덴트 및 짜잘한 포맷팅만 수정했습니다!
=> [WOOCOU-53] ⚙️ chore : 인덴트 및 포매팅 수정

src/main/java/com/coumin/woowahancoupons/coupon/dto/CouponConverter.java, src/main/java/com/coumin/woowahancoupons/coupon/dto/StoreCouponSaveRequestDto.java, src/main/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponService.java, src/main/java/com/coumin/woowahancoupons/domain/coupon/ExpirationPolicy.java, src/test/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponServiceIntegrationTest.java
[WOOCOU-60](https://maenguin.atlassian.net/browse/WOOCOU-60)
전 pr인 탭 인덴트 수정하면서 살펴본 부분들 수정해보았씁니다. 이제 기능구현하겠습니다! 😺 
1. CouponCreateConverter -> CouponConverter
2. 테스트 코드 접근제어자 누락 추가, 사용하지 않는 주입 삭제
3. lint 걸린 newExpirationPeriod() 리팩토링
4. dto 네임 컨벤션 수정
=> [WOOCOU-60] ♻️ refactor : 네이밍 & 린트 리팩토링

src/test/java/com/coumin/woowahancoupons/store/service/SimpleStoreServiceTest.java
[WOOCOU-45](https://maenguin.atlassian.net/browse/WOOCOU-45)
서비스 테스트 코드 추가했습니다!
=> [WOOCOU-45] 🚦 test : 매장 쿠폰 리스트 조회 서비스 테스트 추가

src/main/java/com/coumin/woowahancoupons/store/controller/StoreRestController.java, src/test/java/com/coumin/woowahancoupons/store/controller/StoreRestControllerTest.java
[WOOCOU-46](https://maenguin.atlassian.net/browse/WOOCOU-46)
팀원분들께 질문 : list response도 감싸서 일급 컬렉션 dto로 하는게 좋나요??
=> [WOOCOU-46] ⭐ feat : 매장 쿠폰 리스트 조회 컨트롤러 구현

src/main/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionService.java, src/main/java/com/coumin/woowahancoupons/global/error/ErrorCode.java, src/main/java/com/coumin/woowahancoupons/global/exception/CouponNotFoundException.java, src/main/java/com/coumin/woowahancoupons/global/exception/CustomerNotFoundException.java, src/test/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionServiceTest.java
[WOOCOU-57](https://maenguin.atlassian.net/browse/WOOCOU-57)
* 고객에게 쿠폰 자동 할당 기능 서비스 코드와 테스트를 구현하였습니다.
* 구현할때 조건들이 눈에 밟혀서 추가할까 했는데 기획대로 다음 스프린트때 하는게 좋을것 같아서 일단 현재 구현상태로 올립니다. (이슈로 생성해두겠습니다!)
* 추가적으로 이건 번외인데 getById를 사용할때 잘못된 Id가 들어가면 외래키 제약조건 Exception이 발생하는데 MockMvc로 테스트하면 Exception이 발생해도 ApiResponse success가 true로 나옵니다. @ControllerAdvice가 작동을 안하는건지.. 한번 확인해봐야될것 같습니다.
=> [WOOCOU-57] ⭐ feat : 고객에게 쿠폰 자동 할당 기능 서비스 레이어 구현

src/main/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestController.java, src/main/java/com/coumin/woowahancoupons/coupon/service/CouponRedemptionService.java, src/main/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionService.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestControllerTest.java
[WOOCOU-64](https://maenguin.atlassian.net/browse/WOOCOU-64)
* 고객에게 쿠폰 자동 할당 기능 컨트롤러 코드와 테스트를 구현하였습니다.
* 인터페이스에 누락된 메서드가 있어서 추가했읍니다!
* 컨트롤러 테스트를 추가하면서 현재 주로 사용하고 있는 bdd 컨벤션에 맞게 일부 스타일을 수정했습니다.
=> [WOOCOU-64] ⭐ feat : 고객에게 쿠폰 자동 할당 기능 컨트롤러 레이어 구현

src/main/java/com/coumin/woowahancoupons/coupon/controller/CouponRestController.java, src/main/java/com/coumin/woowahancoupons/coupon/service/CouponService.java, src/main/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponService.java, src/main/java/com/coumin/woowahancoupons/domain/coupon/CouponAdmin.java, src/main/java/com/coumin/woowahancoupons/global/error/ErrorCode.java, src/main/java/com/coumin/woowahancoupons/global/exception/AdminNotFoundException.java, src/test/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponServiceIntegrationTest.java
[WOOCOU-56](https://maenguin.atlassian.net/browse/WOOCOU-56)
mock을 아직 못써서, 예외처리 에러테스트는 만들지 못했습니다.
=> [WOOCOU-56] ⭐ feat : @PostMapping {couponAdminId} 추가

.github/workflows/sonar-build.yml, build.gradle, lombok.config
=> ⭐ feat : jacoco & sonar-cloud 추가

.github/workflows/sonar-build.yml
=> 소나 빌드 브랜치 develop으로 수정

src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRestControllerTest.java
[WOOCOU-50](https://maenguin.atlassian.net/browse/WOOCOU-50)
createAdminCoupon 컨트롤러 추가하였습니다.
=> [WOOCOU-50] 🚦 test : createAdminCoupon 컨트롤러 테스트 추가

.github/workflows/sonar-build.yml
[WOOCOU-67](https://maenguin.atlassian.net/browse/WOOCOU-67)
- 오토매틱 분석 사용(멘토님)
- 소나클라우드 깃허브 액션 pr 이벤트 삭제
=> [WOOCOU-67] ⚙️ chore : 소나클라우드 깃허브 액션 pr 이벤트 삭제

src/main/java/com/coumin/woowahancoupons/coupon/converter/CouponConverter.java, src/main/java/com/coumin/woowahancoupons/coupon/converter/CouponRedemptionConverter.java, src/main/java/com/coumin/woowahancoupons/coupon/dto/CouponRedemptionResponseDto.java, src/main/java/com/coumin/woowahancoupons/coupon/dto/SimpleCouponDto.java, src/main/java/com/coumin/woowahancoupons/coupon/service/CouponRedemptionService.java, src/main/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionService.java, src/main/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponService.java, src/main/java/com/coumin/woowahancoupons/domain/coupon/ExpirationPeriod.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestControllerTest.java, src/test/java/com/coumin/woowahancoupons/coupon/factory/TestCouponFactory.java, src/test/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionServiceTest.java, src/test/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponServiceIntegrationTest.java, src/test/java/com/coumin/woowahancoupons/domain/coupon/CouponRedemptionRepositoryTest.java, src/test/java/com/coumin/woowahancoupons/domain/coupon/CouponRepositoryTest.java, src/test/java/com/coumin/woowahancoupons/store/controller/StoreRestControllerTest.java, src/test/java/com/coumin/woowahancoupons/store/service/SimpleStoreServiceTest.java
[WOOCOU-65](https://maenguin.atlassian.net/browse/WOOCOU-65)
- 컨버터 패키지 따로 뺐습니다!
- findCustomerCouponRedemptions 서비스 메소드 추가했습니다!
- 테스트 코드 작성했습니다.
- 테스트 팩토리 클래스 팩토리 패키지로 이동했습니다.
=> [WOOCOU-65] ⭐ feat : 사용자의 사용가능한 쿠폰 리뎀션 조회 서비스 구현

src/main/java/com/coumin/woowahancoupons/coupon/service/CouponRedemptionService.java, src/main/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionService.java, src/main/java/com/coumin/woowahancoupons/domain/coupon/Coupon.java, src/main/java/com/coumin/woowahancoupons/domain/coupon/CouponRepository.java, src/main/java/com/coumin/woowahancoupons/global/error/ErrorCode.java, src/main/java/com/coumin/woowahancoupons/global/exception/BusinessException.java, src/main/java/com/coumin/woowahancoupons/global/exception/CouponMaxCountOverException.java, src/test/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionServiceTest.java
[WOOCOU-66](https://maenguin.atlassian.net/browse/WOOCOU-66)
* 쿠폰 코드 발행 기능 서비스 레이어 부분을 구현했습니다. (쿠폰 코드 미리 발행해 놓는 관리자용 기능)
* 테스트 코드도 추가했습니다.
* Exception Message를 string format으로 받아서 처리할 수 있는 기능을 추가했습니다.
* 비관적락을 적용했습니다. (쿠폰 할당 count 업데이트용) 
* 관리자 기능이라 락을 걸어도 괜찮을것 같다고 판단했읍니다
=> [WOOCOU-66] ⭐ feat : 쿠폰 코드 발행 기능 서비스 레이어 구현

src/main/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestController.java, src/main/java/com/coumin/woowahancoupons/coupon/dto/CouponIssuanceDto.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestControllerTest.java
[WOOCOU-68](https://maenguin.atlassian.net/browse/WOOCOU-68)
* 쿠폰 코드 발행 기능 컨트롤러 레이어 부분을 구현했습니다. (쿠폰 코드 미리 발행해 놓는 관리자용 기능)
* 테스트 코드도 추가했습니다.
=> [WOOCOU-68] ⭐ feat : 쿠폰 코드 발행 컨트롤러 레이어 구현

build.gradle
[WOOCOU-69](https://maenguin.atlassian.net/browse/WOOCOU-69)
현재 커버리지가 0.9가 되지 않아 빌드가 되지 않습니다
물론 커버리지를 높여야 하지만 0.8 정도가 적당한 것 같아서 pr 올려봅니다!
의견주세요!
=> [WOOCOU-69] ⚙️ chore : jacoco 커버리지 limit 0.8로 수정

src/main/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestController.java, src/main/java/com/coumin/woowahancoupons/coupon/dto/CouponRedemptionResponseDto.java, src/main/java/com/coumin/woowahancoupons/coupon/dto/SimpleCouponDto.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestControllerTest.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRestControllerTest.java
[WOOCOU-63](https://maenguin.atlassian.net/browse/WOOCOU-63)
- 이전 연결된 pr에서 dto의 게터를 깜빡해서 추가했습니다 ㅠ
- 해당 컨트롤러 메서드 및 테스트 코드 추가했습니다.
=> [WOOCOU-63] ⭐ feat : 사용자의 쿠폰 리스트 조회 컨트롤러 추가

src/main/java/com/coumin/woowahancoupons/domain/coupon/Coupon.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestControllerTest.java, src/test/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionServiceTest.java
[WOOCOU-72](https://maenguin.atlassian.net/browse/WOOCOU-72)
* Coupon entity allocatedCount notnull default 0으로 변경하였읍니다.
=> [WOOCOU-72] ♻️ refactor : Coupon entity allocatedCount notnull default 0으로 변경

src/main/resources/application.yml
[WOOCOU-78](https://maenguin.atlassian.net/browse/WOOCOU-78)
테스트코드 시 인코딩(한글깨짐)으로 추가하였습니다. 
이슈 생성하여 PR 날립니다.
=> [WOOCOU-78] ⚙ chore : 응답데이터 Response 인코딩(한글깨짐) 설정

src/main/java/com/coumin/woowahancoupons/coupon/controller/CouponRestController.java, src/main/java/com/coumin/woowahancoupons/coupon/dto/CouponCreateRequestDto.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRestControllerTest.java
[WOOCOU-51](https://maenguin.atlassian.net/browse/WOOCOU-51)
Bean Validation으로 해당 DTO 필드값 검증
해당 필드에 빈 validation이 적절한지 봐주시면 감사하겠습니다.
=> [WOOCOU-51] ⭐ feat : 관리자 쿠폰 생성 Bean Validation 추가

src/main/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestController.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestControllerTest.java
[WOOCOU-75](https://maenguin.atlassian.net/browse/WOOCOU-75)
쿠폰 사용 처리 컨트롤러 구현했습니다!
=> [WOOCOU-75] ⭐ feat : 쿠폰 사용처리 컨트롤러 구현

src/docs/asciidoc/index.adoc, src/main/java/com/coumin/woowahancoupons/WoowahanCouponsApplication.java, src/main/java/com/coumin/woowahancoupons/config/JpaAuditingConfiguration.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CommonDocumentationTest.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponDocumentationTest.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionDocumentationTest.java
[WOOCOU-80](https://maenguin.atlassian.net/browse/WOOCOU-80)
* @EnableJpaAuditing 설정 파일로 분리 했읍니다! (comment를 봐주세욤)
* RestDocs 생성을 위한 Test 클래스를 따로 생성하였습니다.
CommonDocumentationTest : 공통 응답 객체 뽑아내기용
CouponDocumentationTest : CouponRestController용
CouponRedemptionDocumentationTest :CouponRedemptionController용
* index.adoc 파일을 추가했읍니다!
=> [WOOCOU-80] ⭐ feat : RestDocs 추가

src/main/java/com/coumin/woowahancoupons/coupon/dto/CouponCheckRequestDto.java, src/main/java/com/coumin/woowahancoupons/coupon/service/CouponRedemptionService.java, src/main/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionService.java, src/main/java/com/coumin/woowahancoupons/domain/coupon/Coupon.java, src/main/java/com/coumin/woowahancoupons/domain/coupon/CouponRedemption.java, src/main/java/com/coumin/woowahancoupons/domain/store/Brand.java, src/main/java/com/coumin/woowahancoupons/global/error/ErrorCode.java, src/main/java/com/coumin/woowahancoupons/global/exception/CouponIssuerIdNotMatchException.java, src/main/java/com/coumin/woowahancoupons/global/exception/CouponMinOrderPriceNotSatisfyException.java, src/test/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionServiceTest.java
[WOOCOU-76](https://maenguin.atlassian.net/browse/WOOCOU-76)
- CouponCheckRequestDto 추가
- 주문시 해당 쿠폰을 사용할 수 있는지 확인하는 메서드 추가했습니다.
- `checkCouponForUse(Long couponRedemptionId, CouponCheckRequestDto couponCheckRequestDto)`
- couponRedemption의 `verifyForUse(long issuerId, long orderPrice)` 메서드 추가했습니다.
- 관련 에러코드 및 예외처리 추가했습니다.
- 리팩토링 가능한 부분 및 네이밍도 꼭 봐주세요!!
=> [WOOCOU-76] ⭐ feat : 쿠폰 사용 체크 서비스 레이어 구현

src/test/java/com/coumin/woowahancoupons/ApiDocumentationTest.java, src/test/java/com/coumin/woowahancoupons/coupon/document/CommonDocumentationTest.java, src/test/java/com/coumin/woowahancoupons/coupon/document/CouponDocumentationTest.java, src/test/java/com/coumin/woowahancoupons/coupon/document/CouponRedemptionDocumentationTest.java
[WOOCOU-81](https://maenguin.atlassian.net/browse/WOOCOU-81)
- rest doc용 테스트를 따로 document 패키지로 뺐습니다!
- rest docs 모르는게 많아 가볍게 찾아보다 [참고](https://techblog.woowahan.com/2678/) 해서 매번 스프링 컨텍스트를 띄우지 않아도 되는 방법이 있어서 적용해보았습니다!
-저희는 api가 적어서 제 로컬환경에서는 5 ~ 10초 정도의 시간 감소이지만 소개하는 겸 진행해보았습니다.
=> [WOOCOU-81] ♻️ refactor : rest doc 테스트 패키지 & 컨텍스트 하나로 리팩토링

src/main/java/com/coumin/woowahancoupons/coupon/converter/CouponConverter.java, src/main/java/com/coumin/woowahancoupons/coupon/dto/StoreCouponSaveDto.java, src/main/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponService.java, src/test/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponServiceTest.java, src/test/java/com/coumin/woowahancoupons/store/service/SimpleStoreServiceTest.java
[WOOCOU-52](https://maenguin.atlassian.net/browse/WOOCOU-52) 
#WOOCOU-52 close
toentity가 하나뿐이라, 컨버터 전환은 한개만 하는건지 궁금합니다.
=> [WOOCOU-52] ♻️ refactor : DTO & 컨버터 관련 리팩토링

src/main/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestController.java, src/main/java/com/coumin/woowahancoupons/coupon/dto/CouponCheckRequestDto.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestControllerTest.java
[WOOCOU-77](https://maenguin.atlassian.net/browse/WOOCOU-77)
- 컨트롤러 및 테스트 코드 구현했습니다!
=> [WOOCOU-77] ⭐ feat : 쿠폰 사용 가능 유무 확인 컨트롤러 추가

.github/workflows/gradle.yml
[WOOCOU-83](https://maenguin.atlassian.net/browse/WOOCOU-83)
- github aciton yml 추가했습니다.
=> [WOOCOU-83] 🚀 CI : github action CI 추가

src/docs/asciidoc/index.adoc, src/test/java/com/coumin/woowahancoupons/coupon/document/ApiDocumentationTest.java, src/test/java/com/coumin/woowahancoupons/coupon/document/CommonDocumentationTest.java, src/test/java/com/coumin/woowahancoupons/coupon/document/CouponDocumentationTest.java, src/test/java/com/coumin/woowahancoupons/coupon/document/CouponRedemptionDocumentationTest.java, src/test/java/com/coumin/woowahancoupons/coupon/document/StoreDocumentationTest.java
[WOOCOU-82](https://maenguin.atlassian.net/browse/WOOCOU-82)
* 누락되었던 매장의 쿠폰 조회 api doc과 신규 쿠폰 사용 가능 체크 api doc을 추가하였습니다.
* ApiDocumentationTest를 document 패키지 안으로 이동시켰습니다.
=> [WOOCOU-82] 📖 docs : 매장의 쿠폰 조회, 쿠폰 사용 가능 체크 api docs 추가

src/main/java/com/coumin/woowahancoupons/coupon/service/SimpleCouponRedemptionService.java, src/main/java/com/coumin/woowahancoupons/domain/coupon/CouponRedemption.java, src/test/java/com/coumin/woowahancoupons/coupon/controller/CouponRedemptionRestControllerTest.java
[WOOCOU-84](https://maenguin.atlassian.net/browse/WOOCOU-84)
쿼리로 처리할까 고민했지만 타임존 관련 확장성 및 쿼리는 단순화하게 가져오기 위해서 코드로 처리했습니다!
=> [WOOCOU-84] ⭐ feat : 사용기한이 만료된 사용자의 쿠폰은 조회 시 반환하지 않도록 수정

.github/workflows/ci-build.yml, .github/workflows/deploy.yml
깃허브 액션에서 빌드한 jar s3에 업로하드하는 yml 추가했습니다.
=> 🚀 CI : Add deploy.yml for github aciton jar upload to s3

.github/workflows/deploy.yml, appspec.yml
=> 🔖 Release : 1.1.3

.github/workflows/deploy.yml
=> 🐞 fix : deploy.yml s3 스페이스 삭제

.github/workflows/deploy.yml
🐞 fix : Add copy appspec.yml in deploy.yml
=> 🐞 fix : Add copy appspec.yml in deploy.yml
